# EXIT FILE

print("~ ~        YOU HAVE SUCCESSFULLY EXITED THE PROGRAM       ~ ~")
print()
print("     PROTECT YOURSELF AND OTHERS AROUND YOU BY TAKING APPROPRIATE PRECAUTIONS.")
print("     FOLLOW ADVICE PROVIDED BY YOUR LOCAL HEALTH AUTHORITY.   ")
print("_"*90)
print()
print("~ TO PREVENT THE SPREAD OF COVID-19 ~")
print()
print("1) Clean your hands often for 40-50 seconds." ,"\n","Use soap and water, or an alcohol-based hand rub.")
print("2)Maintain a safe distance from anyone who is coughing or sneezing.")
print("3)Wear a mask when physical distancing is not possible.")
print("4)Don’t touch your eyes, nose or mouth with dirty hands.")
print("5)Cover your nose and mouth with your bent elbow or a tissue when you cough or sneeze.")
print("6)Stay home if you feel unwell.")
print("7)If you have a fever, cough and difficulty breathing, seek medical attention.","\n","Calling in advance allows your healthcare provider to quickly direct you to the right health facility. ")
print()
print("THIS PROTECTS YOU AND PREVENTS THE SPREAD OF VIRUSES AND OTHER INFECTIONS.")
print("_"*90)
print()
print("~ ~      GUIDELINES  BY THE GOVERNMENT      ~ ~")
print()
print("1)Persons above 65 years of age, persons with comorbidities, pregnant women are advised to stay at home","\n","Except for essential and health purposes")
print("2)Individuals must maintain a minimum distance of 6 feet in public places as far as feasible.")
print("3)Use of face covers/masks to be mandatory")
print("4)Practice frequent hand washing with soap (for at least 40-60 seconds) even when hands are not visibly dirty")
print("5)Use of alcohol-based hand sanitizers (for at least 20 seconds) can be made wherever feasible")
print("6)These measures need to be observed by all (employees and visitors) at all times.")
print("7)Follow the advice provided by your local health authority.")

